steps:
  - label: run bats tests
    plugins:
      docker-compose#v2.4.0:
        run: tests

  - label: ":bash: Shellcheck"
    plugins:
      shellcheck#v1.0.1:
        files:
          - hooks/*

  - label: ":sparkles: Linter"
    plugins:
      plugin-linter#v2.0.0:
        id: golang-cross-compile

  - wait
  - label: ":pipeline: example 1"
    plugins:
      ${BUILDKITE_REPO}#${BUILDKITE_COMMIT}:
        debug: true
        build: ./tests/helloworld
        import: github.com/buildkite/example
        targets:
          - version: 1.10.2
            goos: linux
            goarch: amd64
          - version: 1.10.2
            goos: windows
            goarch: amd64
          - version: 1.10.2
            goos: darwin
            goarch: amd64




