steps:
  - label: run bats tests
    plugins:
      - plugin-tester#v1.1.0: ~

  - label: ":bash: Shellcheck"
    plugins:
      - shellcheck#v1.3.0:
          files:
            - hooks/*

  - label: ":sparkles: Linter"
    plugins:
      - plugin-linter#v3.2.0:
          id: golang-cross-compile

  - wait
  - label: ":pipeline: example 1"
    plugins:
      - ${BUILDKITE_REPO}#${BUILDKITE_COMMIT}:
          debug: true
          build: ./tests/helloworld
          import: github.com/buildkite-plugins/golang-cross-compile-buildkite-plugin
          targets:
            - version: "1.20"
              goos: linux
              goarch: amd64
            - version: "1.20"
              goos: windows
              goarch: amd64
            - version: "1.20"
              goos: darwin
              goarch: amd64
